pipeline:
  validate-and-test:
    image: rust:1.97-alpine
    commands:
      # Install runtime dependencies inside the isolated container 
      # (apk is the package manager in Alpine Linux)
      - apk add --no-cache git musl-dev bash
      
      # Install rsigma binary
      - cargo install rsigma --version 0.23.0
      
      # The actual unit tests.
      # These are kept in a separate file to enable local testing as well.
      - bash ./tests/rule_tests.sh
